# Generated by Django 5.0.4 on 2024-04-26 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('COD_BRAND', models.AutoField(primary_key=True, serialize=False)),
                ('BRAND', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('COD_CAR', models.AutoField(primary_key=True, serialize=False)),
                ('MODEL', models.CharField(max_length=200)),
                ('FACTORY_YEAR', models.IntegerField()),
                ('MODEL_YEAR', models.IntegerField()),
                ('VALUE', models.FloatField(blank=True, null=True)),
                ('BRAND', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='car_bland', to='cars.brand')),
            ],
        ),
    ]
