# Generated by Django 5.0.4 on 2024-04-26 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='PHOTO',
            field=models.ImageField(null=True, upload_to='car/'),
        ),
        migrations.AddField(
            model_name='car',
            name='PLATES',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
