# Generated by Django 5.0.4 on 2024-04-28 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_car_photo_car_plates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='PHOTO',
            field=models.ImageField(blank=True, null=True, upload_to='car/'),
        ),
    ]
