# Generated by Django 5.0.4 on 2024-05-07 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_car_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='PHOTO',
            field=models.ImageField(default=1, upload_to='car/'),
            preserve_default=False,
        ),
    ]
