# Generated by Django 5.0.4 on 2024-05-23 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_carinventory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='BRAND',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='COD_BRAND',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='BRAND',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='FACTORY_YEAR',
            new_name='factory_year',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='COD_CAR',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='MODEL',
            new_name='model',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='MODEL_YEAR',
            new_name='model_year',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='PHOTO',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='PLATES',
            new_name='plate',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='VALUE',
            new_name='value',
        ),
    ]
