# Generated by Django 5.0.4 on 2024-05-23 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_rename_brand_brand_brand_rename_cod_brand_brand_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
